version: '2'
services:
  vulnerable_node:
    restart: always
    build: .
    ports:
      - "3000:3000"
#    links:
#      - postgres_db:postgres_db
    depends_on:
      - postgres_db

  postgres_db:
    restart: always
    build: ./services/postgresql
    ports:
      - "5432:5432"
  
  vulnerable-package:
    restart: always
    image: ghcr.io/sabreen-parveen/vulnerable:2.4
    ports:
      - "80:80"

  vulnerable:
    restart: always
    image: vulnerables/web-dvwa:1.9
    ports:
      - "80:80"
  vulnerable-node:
    restart: always
    image: node:10.22.0-jessie
    ports:
      - "80:80"
  
